### PR TITLE
fix issue 2. GENERATE_INTEGERS lower and upper integer.

### PR DESCRIPTION
**Pull request by ZodPSC**

### CODE REVIEW

**Comment by andre15silva** [comment]
Hi @ZodPSC !

Seems like you are dealing with a different spec when compared with the original HumanEval sample.

See https://huggingface.co/datasets/openai/openai_humaneval/viewer/openai_humaneval/test?q=generate_integers&row=163

The example `// generate_integers(10, 14) => []` is indeed correct. The spec says "return even digits between a and b" and is non-inclusive.

**Comment by ZodPSC** [comment]
Now I understand. I corrected it.

2<=x<=8
2<=a<=8 and 2<=b<=8 for their use

in mathematics:
2n, n &#8712; [2, 8]

**Comment by andre15silva** [comment]
Yes, exactly.

But now the code you are suggesting for the buggy function is the same as the code in the correct function (see https://github.com/ASSERT-KTH/human-eval-java/blob/main/src/main/java/humaneval/correct/GENERATE_INTEGERS.java).

Am I missing something here?

**Comment by ZodPSC** [comment]
lower = max(2, min(a, b)) upper = min(8, max(a, b)) return [i for i in range(lower, upper+1) if i % 2 == 0]

def check(candidate): # Check some simple cases assert candidate **(2, 10)** == **[2, 4, 6, 8]**, "Test 1" assert candidate **(10, 2)** == **[2, 4, 6, 8]**, "Test 2" assert candidate**(132, 2)** == **[2, 4, 6, 8]**, "Test 3" assert candidate **(17,89)** == **[]**, "Test 4" # Check some edge cases that are easy to work out by hand. assert True, "This prints if this assert fails 2 (also good for debugging!)"

**(2, 10)** == **[2, 4, 6, 8]**
**(10, 2)** == **[2, 4, 6, 8]**
**(132, 2)** == **[2, 4, 6, 8]**
**(17,89)** == **[]**

yes it turns out that the source code works correctly. (as intended by the creator)
or the problem statement is incorrect - and the documentation needs to be corrected.

mb i closing PR?

**Comment by andre15silva** [comment]
Yes, we can close the PR!

**Comment by BEbillionaireUSD** [comment]
Thanks for this PR. I think I misunderstood the original description. I guess "even digits" are defined as [0, 2, 4, 6, 8], so if the lower bound is larger than 8, then it should return an empty list.

**Pull request closed without merging**
