### PR TITLE
1. Fix two errors in previous dataset.

### PR DESCRIPTION
**Pull request by Feng-Jay**
2. Add one json file that contains the buggy function of each bug.

FIX ERROR1:
the buggy lines of `MATCH_PARENS` in `src/humaneval_loc.txt` is wrong, it should be 22-24 lines.

FIX ERROR2:
there is a typo error of ISCUBE bug, Both the original humaneval dataset and javaDoc in the corresponding java file indicate the method name should be `iscube` while it was `iscude`, I have modified related files: `src/main/java/humaneval/buggy/ISCUBE.java`
`src/main/java/humaneval/correct/ISCUBE.java`
`src/test/java/humaneval/TEST_ISCUBE.java`
And I have run the test-suites to ensure the validity of these modifications

### CODE REVIEW

**Comment by Feng-Jay** [comment]
hi! Thank you for maintaining the dataset!
I'm using `humaneval-java`and found there are some tiny errors in it. I have made above modifications and I hope you can confirm them! 😸
I have submitted a PR to Professor Tan's [repo](https://github.com/lin-tan/clm/pull/6), but since Professor Tan did not open a separate humaneval-java repository (and I first found humaneval-java from this repository), I hope you can confirm these changes.
Looking forward to your promptly reply!

**Comment by monperrus** [comment]
Thanks for the contribution @Feng-Jay 

Is the JSON file only a copy of the Java files, or does it contain additional unique information? Could you add the script to generate it?

**Comment by Feng-Jay** [comment]
Thank you for your reply @monperrus !

Since many APR methods use function-level defects for evaluation, this JSON file directly provides the corresponding buggy function for each bug, along with the line-ranges of this function in the buggy file and the fixed version of the function. 

 I use JDT for the extraction process, extracting the buggy functions which contain the buggy lines provided in `/src/main/java/humaneval/humaneval_loc.txt`, following a logic similar to this repository (https://github.com/ASSERT-KTH/java-extractor).

To be more clear, I provide a piece of JDT visitor implementation here:

 ```java
 CompilationUnit cu = (CompilationUnit) parser.createAST(null);
        cu.accept(new ASTVisitor() {
                    @Override
                    public boolean visit(MethodDeclaration node){
                        int beginLine = cu.getLineNumber(node.getStartPosition());
                        int endLine = cu.getLineNumber(node.getStartPosition() + node.getLength());
                        boolean condition = methodName.equals(" ") ? beginLine <= baselineBegin && endLine >= baselineEnd : node.getName().toString().equals(methodName);
                        if (condition){
                            final_out_begin = beginLine;
                            final_out_end = endLine;
                            methodName = node.getName().toString();
                            return true;
                        }
                        return true;
                    }
                }
        );
```
It first extracts the buggy function which `beginLine <= baselineBegin && endLine >= baselineEnd` (contains the all buggy content)
Then it extracts the fixed function which have the same function name `node.getName().toString().equals(methodName)`.

**Comment by monperrus** [comment]
LGTM, will merge unless @andre15silva raises concerns

**Comment by andre15silva** [comment]
LGTM, thanks @Feng-Jay!

**Pull request merged**
